// AUTH
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_RESET = "AUTH_RESET"

// QUEUE
export const CHANGE_QUEUE_COUNT = "CHANGE_QUEUE_COUNT"

// LOGOUT
export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

// AUTOIN
export const AUTOIN_START = "AUTOIN_START"
export const AUTOIN_PLAY = "AUTOIN_PLAY"
export const AUTOIN_PAUSE = "AUTOIN_PAUSE"

export const INCREMENT = "INCREMENT";
export const INCREMENT_COUNTER_BY_5 = "INCREMENT_COUNTER_BY_5";

// CONTACT
export const CONTACT_ADD = "CONTACT_ADD"
export const CONTACT_REMOVEALL = "CONTACT_REMOVEALL"
export const CONTACT_SETCURRENT = 'CONTACT_SETCURRENT'
export const CONTACT_SETLASTCHAT = 'CONTACT_SETLASTCHAT'
export const CONTACT_UPDATECOUNT = 'CONTACT_UPDATECOUNT'
export const CONTACT_RESETCOUNT = 'CONTACT_RESETCOUNT'


// DIALOG
export const GETDIALOG_START = "GETDIALOG_START"
export const GETDIALOG_SUCCESS = "GETDIALOG_SUCCESS"
export const GETDIALOG_FAIL = "GETDIALOG_FAIL"

export const SEND_DIALOG_START = "SEND_DIALOG_START"
export const SEND_DIALOG_SUCCESS = "SEND_DIALOG_SUCCESS"
export const SEND_DIALOG_FAIL = "SEND_DIALOG_FAIL"

export const UPDATE_DIALOG_MESSAGE = "UPDATE_DIALOG_MESSAGE"

export const RESET_DIALOG = "RESET_DIALOG"



// PROFILE
export const GETPROFILE_START = "GETPROFILE_START"
export const GETPROFILE_SUCCESS = "GETPROFILE_SUCCESS"
export const GETPROFILE_FAIL = "GETPROFILE_FAIL"
export const PROFILE_CHANGE_TAB = "PROFILE_CHANGE_TAB"
export const PROFILE_RESET_TAB = "PROFILE_RESET_TAB"

export const RESET_PROFILE = "RESET_PROFILE"




